apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':common:types')
    implementation project(':common:web')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    runtimeOnly 'com.mysql:mysql-connector-j'
}
